### ISSUE TITLE
Plugin fails with java.io.IOException

### ISSUE THREAD

**Issue by vjuranek** [vjuranek/radargun-plugin#36]
Running any script fails with
```
java.io.IOException: Cannot run program "radargun-plugin/work/workspace/radargun3.0-test/radargun_master4296330238282102242.sh" (in directory "radargun-plugin/work/workspace/radargun3.0-test/tmp"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at hudson.Proc$LocalProc.<init>(Proc.java:244)
        at hudson.Proc$LocalProc.<init>(Proc.java:216)
        at hudson.Launcher$LocalLauncher.launch(Launcher.java:803)
        at hudson.Launcher$ProcStarter.start(Launcher.java:381)
        at org.jenkinsci.plugins.radargun.NodeRunner.call(NodeRunner.java:35)
        at org.jenkinsci.plugins.radargun.NodeRunner.call(NodeRunner.java:11)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 10 more

```

**Comment by vjuranek** [comment]
Was caused by non-exiting process working directory, configured directly in the job. Added check that workspace exists in ec67a8a219e7780b622650c1d7c1bdf2d6102c39
