### ISSUE TITLE
ScriptsourceTest fails randomly

### ISSUE THREAD

**Issue by vjuranek** [vjuranek/radargun-plugin#63]
Fails randomly with 
```
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [7]; expected:<key[1="value1" key2="" key3="value3]"> but was:<key[3="value3" key2="" key1="value1]">
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:50)
	at org.junit.Assert.internalArrayEquals(Assert.java:473)
	at org.junit.Assert.assertArrayEquals(Assert.java:265)
	at org.junit.Assert.assertArrayEquals(Assert.java:280)
	at org.jenkinsci.plugins.radargun.config.ScriptsourceTest.testGetNodeCmdLine(ScriptsourceTest.java:73)
```
and
```
org.junit.ComparisonFailure: expected:<key[1="value1" key2="" key3="value3]"> but was:<key[3="value3" key2="" key1="value1]">
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.jenkinsci.plugins.radargun.config.ScriptsourceTest.testPrepareEnvVars(ScriptsourceTest.java:79)
```

**Comment by vjuranek** [comment]
Still happening
