### ISSUE TITLE
Changes in 1.4 have broken RG execution

### ISSUE THREAD

**Issue by vjuranek** [vjuranek/radargun-plugin#74]
While everything works fine with RG plugin 1.3, with 1.4 jobs fail with exception like one bellow. It looks like it's cause by switching to completable future in 7dc46661241ec4fa3e46d11c03573722ff1cb443 as it looks like an issue in synchronization a waiting for other futures.

```
java.io.IOException: 14 slaves haven't connected within timeout!
	at org.radargun.RemoteSlaveConnection.establish(RemoteSlaveConnection.java:112) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.Master.run(Master.java:59) [radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.LaunchMaster.main(LaunchMaster.java:34) [radargun-core-3.0.0-SNAPSHOT.jar:?]
17:02:31,117 WARN  [org.radargun.RemoteSlaveConnection] (main) Failed to send termination to slaves.
java.lang.NullPointerException: null
	at org.radargun.RemoteSlaveConnection$SlaveRecord.access$100(RemoteSlaveConnection.java:63) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.RemoteSlaveConnection.mcastBuffer(RemoteSlaveConnection.java:201) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.RemoteSlaveConnection.mcastObject(RemoteSlaveConnection.java:211) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.RemoteSlaveConnection.release(RemoteSlaveConnection.java:357) [radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.Master.run(Master.java:155) [radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.LaunchMaster.main(LaunchMaster.java:34) [radargun-core-3.0.0-SNAPSHOT.jar:?]
```

**Comment by vjuranek** [comment]
Probably the root cause is that I forgot to pass `executorService` into `CompletableFuture.supplyAsync` in `AbstractRgProcess`, and thus default `ForkJoinPool` was used with default parallelism level of `Runtime#availableProcessors`, so couple of processes has been started and once they timed out and feed threads, remaining processes had been started.
